const page = location.pathname.split('/').pop() || 'index.html';
const cartKey = 'jaikri-cart';
const products = {
  solara:{name:'Solara Dress', price:4800, size:'S', image:'https://images.unsplash.com/photo-1525507119028-ed4c629a60a3?auto=format&fit=crop&w=700&q=85'},
  raas:{name:'Raas Overshirt', price:3900, size:'M', image:'https://images.unsplash.com/photo-1485968579580-b6d095142e6e?auto=format&fit=crop&w=700&q=85'},
  mira:{name:'Mira Trousers', price:4200, size:'M', image:'https://images.unsplash.com/photo-1496217590455-aa63a8350eea?auto=format&fit=crop&w=700&q=85'},
  nadi:{name:'Nadi Kurta', price:3600, size:'S', image:'https://images.unsplash.com/photo-1506629905607-d405b7a0b4c8?auto=format&fit=crop&w=700&q=85'}
};
const getCart = () => JSON.parse(localStorage.getItem(cartKey) || '[]');
const saveCart = cart => { localStorage.setItem(cartKey, JSON.stringify(cart)); updateBag(); };
const cartQty = () => getCart().reduce((n,item) => n + item.qty, 0);
const money = n => `₹${n.toLocaleString('en-IN')}`;

function header() {
  const active = (file, label) => `<a href="${file}" class="${page === file ? 'active' : ''}">${label}</a>`;
  return `<a class="skip-link" href="#main">Skip to main content</a><div class="promo">Complimentary delivery over ₹4,000 <span>•</span> Easy 14-day returns</div><header class="site-header"><button class="icon-btn mobile-menu" aria-label="Open menu" aria-expanded="false"><span></span><span></span></button><a class="wordmark logo" href="index.html" aria-label="Jaikri home"><img src="assets/jaikri-mark.svg" alt="Jaikri"></a><nav class="nav" aria-label="Main navigation">${active('shop.html','Shop')}${active('collections.html','Collections')}${active('about.html','Our world')}<a href="help.html">Journal</a><button class="nav-ai text-link" type="button">Ask JAI</button></nav><div class="header-tools"><a class="icon-btn search-tool" href="shop.html" aria-label="Search products"><svg viewBox="0 0 24 24"><circle cx="10.8" cy="10.8" r="6.2"></circle><path d="m16 16 4.3 4.3"></path></svg></a><a class="icon-btn" href="account.html" aria-label="Your account"><svg viewBox="0 0 24 24"><circle cx="12" cy="8" r="3.5"></circle><path d="M5.5 20c.7-3.3 3-5 6.5-5s5.8 1.7 6.5 5"></path></svg></a><a class="icon-btn" href="cart.html" aria-label="Shopping bag"><svg viewBox="0 0 24 24"><path d="M5 8.5h14l-1 11H6l-1-11Z"></path><path d="M9 9V6.8a3 3 0 0 1 6 0V9"></path></svg><span class="bag-number">0</span></a></div></header>`;
}
function footer() { return `<section class="newsletter"><p class="eyebrow">A note from the studio</p><h2>Good things, <em>occasionally.</em></h2><p>New pieces, studio notes and considered inspiration—sent slowly.</p><form class="newsletter-form"><label class="sr-only" for="newsletter-email">Email address</label><input id="newsletter-email" type="email" placeholder="Your email address" required><button aria-label="Subscribe" type="submit">→</button></form><p class="newsletter-note" aria-live="polite"></p></section><footer class="site-footer"><a class="wordmark logo" href="index.html"><img src="assets/jaikri-mark.svg" alt="Jaikri"></a><div class="footer-column"><h3>Customer care</h3><a href="help.html">Help & FAQs</a><a href="policies.html#shipping">Shipping & returns</a><a href="policies.html#size">Size guide</a><a href="contact.html">Contact us</a></div><div class="footer-column"><h3>About Jaikri</h3><a href="about.html">Our story</a><a href="collections.html">Collections</a><a href="shop.html">Shop all</a><a href="account.html">My account</a><a href="policies.html#privacy">Privacy</a></div><div class="footer-bottom"><span>© 2026 Jaikri</span><span>Made in small batches, in India</span></div></footer>`; }
function ai() { return `<button class="ai-bubble nav-ai" aria-label="Open JAI personal stylist"><span class="ai-dot"></span> Ask JAI</button><div class="ai-modal" aria-hidden="true"><section class="ai-panel" aria-labelledby="jai-title"><div class="ai-panel-header"><div><p class="eyebrow">Personal style companion</p><h2 id="jai-title">Hello, I’m JAI.</h2></div><button class="icon-btn close-ai" aria-label="Close stylist">×</button></div><div class="chat" aria-live="polite"><p class="message">Tell me the occasion, weather, or how you want to feel. I’ll create a Jaikri edit for you.</p></div><form class="chat-form"><label class="sr-only" for="jai-question">Ask JAI</label><input id="jai-question" placeholder="Ask JAI anything…" autocomplete="off"><button aria-label="Send question">→</button></form></section></div><div class="toast" role="status" aria-live="polite"></div>`; }
document.body.insertAdjacentHTML('afterbegin', header()); document.body.insertAdjacentHTML('beforeend', footer() + ai());
function updateBag() { document.querySelectorAll('.bag-number').forEach(el => el.textContent = cartQty()); }
function toast(message) { const el = document.querySelector('.toast'); el.textContent = message; el.classList.add('show'); setTimeout(() => el.classList.remove('show'), 2600); }
function addToCart(id) { const cart = getCart(); const line = cart.find(item => item.id === id); if (line) line.qty += 1; else cart.push({id, qty:1}); saveCart(cart); toast(`${products[id].name} added to your bag`); }
document.addEventListener('click', event => { const add = event.target.closest('[data-add]'); if (add) { addToCart(add.dataset.add); } });
document.querySelector('.mobile-menu')?.addEventListener('click', event => { const nav = document.querySelector('.nav'); const open = nav.classList.toggle('open'); event.currentTarget.setAttribute('aria-expanded', open); });
const modal = document.querySelector('.ai-modal'); document.querySelectorAll('.nav-ai').forEach(b => b.addEventListener('click', () => { modal.classList.add('open'); modal.setAttribute('aria-hidden','false'); document.querySelector('#jai-question').focus(); })); document.querySelector('.close-ai')?.addEventListener('click', () => { modal.classList.remove('open'); modal.setAttribute('aria-hidden','true'); }); modal?.addEventListener('click', e => { if(e.target === modal) modal.classList.remove('open'); });
document.querySelector('.chat-form')?.addEventListener('submit', event => { event.preventDefault(); const input = document.querySelector('#jai-question'); const q = input.value.trim(); if(!q) return; document.querySelector('.chat').insertAdjacentHTML('beforeend', `<p class="message user"></p>`); document.querySelector('.chat .message.user:last-child').textContent = q; const answer = /wedding/i.test(q) ? 'For a wedding, I’d pair the Solara Dress with the Raas Overshirt for an effortless second layer.' : /weekend|travel/i.test(q) ? 'For an easy weekend, start with the Raas Overshirt and Mira Trousers—natural layers that travel beautifully.' : 'I’d begin with our considered staples: one easy shirt, one relaxed trouser, and a dress you can return to often.'; setTimeout(() => { document.querySelector('.chat').insertAdjacentHTML('beforeend', `<p class="message"></p>`); document.querySelector('.chat .message:last-child').textContent = answer; }, 260); input.value=''; });
document.querySelector('.newsletter-form')?.addEventListener('submit', event => { event.preventDefault(); event.currentTarget.nextElementSibling.textContent = 'Thank you — you are on the Jaikri list.'; event.currentTarget.reset(); }); updateBag();
